services:
  minio1:
    image: minio/minio
    restart: always
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ./ec/data11:/data1
      - ./ec/data12:/data2
    extra_hosts:
      xminio1: 1.1.1.1
      xminio2: 2.2.2.2
    command: >
      server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
      http://minio1:9000/data{1...2}
      http://minio2:9000/data{1...2}

    stdin_open: true
    tty: true

  minio2:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ./ec/data21:/data1
      - ./ec/data22:/data2

    command: >
      server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
      http://minio1:9000/data{1...2}
      http://minio2:9000/data{1...2}

    stdin_open: true
    tty: true

